# Generated by Django 4.2.11 on 2024-05-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Location',
        ),
    ]
